parameters:

    fixture:
        roles:
            0:
                name: user
                role: ROLE_USER
            1:
                name: teacher
                role: ROLE_TEACHER
        users:
            0:
                username: 'Денис'
                email: denis@test.ru
                password: 'password'
                roles: [0]
            1:
                username: 'Владимир'
                email: vladimir@test.ru
                password: 'password'
                roles: [0, 1]
        tests:
            0:
                name: 'Тест по истории'
            1:
                name: 'Тест по информатике'
        questions:
            0:
                name: 'Когда закончилась вторая мировая война?'
                parent: 0
            1:
                name: 'Где произошло Ледовое побоище?'
                parent: 0
            2:
                name: 'Кто разработал проект универсальной цифровой вычислительной машины — прообраз современной ЭВМ?'
                parent: 1
            3:
                name: 'Что такое файл?'
                parent: 1
            4:
                name: 'Выберите программы которые являются Web-серверами:'
                parent: 1
            5:
                name: 'Что такое файл?'
                parent: 1
            6:
                name: 'Назовите известные вам операционные системы:'
                parent: 1
            7:
                name: 'Верно ли следующее утверждение: "C++ — компилируемый статически типизированный язык программирования общего назначения"?'
                parent: 1
        answers:
            0:
                name: '9 мая 1945 года'
                is_valid: 0
                parent: 0
            1:
                name: '2 сентября 1945 года'
                is_valid: 1
                parent: 0
            2:
                name: '2 октября 1945 года'
                is_valid: 0
                parent: 0
            3:
                name: 'река Нева'
                is_valid: 0
                parent: 1
            4:
                name: 'Ладожское озеро'
                is_valid: 0
                parent: 1
            5:
                name: 'Чудское озеро'
                is_valid: 1
                parent: 1
            6:
                name: 'Ча́рльз Бэ́ббидж'
                is_valid: 1
                parent: 2
            7:
                name: 'Альбе́рт Эйнште́йн'
                is_valid: 0
                parent: 2
            8:
                name: 'Джон фон Не́йман'
                is_valid: 0
                parent: 2
            9:
                name: 'Nginx'
                is_valid: 1
                parent: 4
            10:
                name: 'SMTP'
                is_valid: 0
                parent: 4
            11:
                name: 'Apache'
                is_valid: 1
                parent: 4
            12:
                name: 'FTP'
                is_valid: 0
                parent: 4
            13:
                name: 'Да'
                is_valid: 1
                parent: 7
            14:
                name: 'Нет'
                is_valid: 0
                parent: 7

    errors:
        test:
            unavailable: 'Данный тест недоступен!'
            save: 'При сохранении результатов тестирования произошла ошибка!'

services:
    denis_d_test.test:
        class: Denis\DTestBundle\Services\Test
        arguments: [@doctrine, @service_container, @security.context]

    denis_d_test.user:
        class: Denis\DTestBundle\Services\User
        arguments: [@doctrine, @service_container, @security.context]

    denis_d_test.form.type.auth:
        class: Denis\DTestBundle\Form\AuthType
        tags:
            - { name: form.type, alias: userform }

    denis_d_test.listener.security:
        class: Denis\DTestBundle\EventListener\SecurityListener
        scope: request
        arguments: [@service_container, @security.context, @event_dispatcher]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin}
