<?php

namespace Denis\DTestBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\QueryBuilder;

/**
 * QuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsRepository extends EntityRepository
{
	public function getQuestionsWithAnswers($testId) {
		if(empty($testId))
			return [];

		$querybuilder = $this->createQueryBuilder('q')
			->leftJoin('q.answers', 'a')
            ->where('q.testsId = :testId')
            ->select('q, a')
            ->setParameter(':testId', $testId);

        return $querybuilder->getQuery()->getArrayResult();
	}
}
